### PR TITLE
feat: fix epoch params

### LINKED ISSUE #109: chore: Move mustParseRFC3339 function to utils
## Summary

Currently, `mustParseRFC3339` function is used in many different tests. 

## Proposal

I propose to move the function to `types/utils.go`.
 

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

### PR DESCRIPTION
**Pull request by kogisin**
## Description

This PR is implemented by following the approach 1 (See the issue #96). 
It adds `CurrentEpochDays` global parameter for key store prefix and use it in `EndBlocker` to handle reward distribution. 

closes: #96 

## Tasks

- [x] Add CurrentEpochDays (approach 1) or EpochEra (approach 2)
- [x] Rename `EpochDays` to `NextEpochDays` in params and fix logics related to it
- [x] Update spec and description
- [x] Write test codes

## Additional works

- [x] Add tests for key store prefixes
- [x] Add handler tests to improve code coverage (as well as to understand the F1 logic better)
- [x] Closes #109
---

Before we can merge this PR, please make sure that all the following items have been
checked off. If any of the checklist items are not applicable, please leave them but
write a little note why.

- [x] Appropriate labels applied
- [x] Targeted PR against correct branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Code follows the [module structure standards](https://github.com/cosmos/cosmos-sdk/blob/master/docs/building-modules/structure.md).
- [x] Wrote unit and integration
- [x] Updated relevant documentation (`docs/`) or specification (`x/<module>/spec/`)
- [x] Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code).
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Review `Codecov Report` in the comment section below once CI passes

### CODE REVIEW

**Comment by dongsam** [comment]
https://github.com/tendermint/farming/pull/98 just merged, so It would be better to merge master first

File: x/farming/abci_test.go [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+
+		currentEpochDays := suite.keeper.GetCurrentEpochDays(suite.ctx)
+
+		t2, _ := suite.keeper.GetLastEpochTime(suite.ctx)
+		if t2.After(lastEpochTime) {
+			suite.Require().GreaterOrEqual(t2.Sub(lastEpochTime).Hours(), float64(nextEpochDays*24))
+			suite.Require().Equal(uint32(7), currentEpochDays)
+		}
+	}
+}
```
Comment (dongsam) [inline x/farming/abci_test.go:84]:
```suggestion
func (suite *ModuleTestSuite) TestEndBlockerEpochDaysTest() {
	epochDaysTest := func(formerEpochDays, targetNextEpochDays uint32) {
		suite.SetupTest()
		params := suite.keeper.GetParams(suite.ctx)
		params.NextEpochDays = formerEpochDays
		suite.keeper.SetParams(suite.ctx, params)
		suite.keeper.SetCurrentEpochDays(suite.ctx, formerEpochDays)

		t := types.ParseTime("2021-08-01T00:00:00Z")
		suite.ctx = suite.ctx.WithBlockTime(t)
		farming.EndBlocker(suite.ctx, suite.keeper)

		lastEpochTime, _ := suite.keeper.GetLastEpochTime(suite.ctx)

		for i := 1; i < 200; i++ {
			t = t.Add(1 * time.Hour)
			suite.ctx = suite.ctx.WithBlockTime(t)
			farming.EndBlocker(suite.ctx, suite.keeper)

			if i == 10 { // 10 hours passed
				params := suite.keeper.GetParams(suite.ctx)
				params.NextEpochDays = targetNextEpochDays
				suite.keeper.SetParams(suite.ctx, params)
			}

			currentEpochDays := suite.keeper.GetCurrentEpochDays(suite.ctx)

			t2, _ := suite.keeper.GetLastEpochTime(suite.ctx)
			if uint32(i) == formerEpochDays*24 {
				suite.Require().True(t2.After(lastEpochTime))
				suite.Require().Equal(t2.Sub(lastEpochTime).Hours(), float64(formerEpochDays*24))
				suite.Require().Equal(targetNextEpochDays, currentEpochDays)
			}

			if uint32(i) == formerEpochDays*24+targetNextEpochDays*24 {
				suite.Require().Equal(t2.Sub(lastEpochTime).Hours(), float64(currentEpochDays*24))
				suite.Require().Equal(targetNextEpochDays, currentEpochDays)
			}
			lastEpochTime = t2
		}
	}

	// increasing case
	epochDaysTest(1, 7)

	// decreasing case
	epochDaysTest(7, 1)
	
	// stay case
	epochDaysTest(1, 1)
}
```

I think this will make the test assertion clearer and more reusable.

**Review by dongsam — CHANGES_REQUESTED** [review]
If it seems like it's going to end soon, I think it'd be nice to add query and cli for `Current EpochDays`.

File: x/farming/keeper/epoch.go [hunk 2]
```diff
@@ -44,3 +44,28 @@ func (k Keeper) AdvanceEpoch(ctx sdk.Context) error {
...
 }
+
+// GetCurrentEpochDays returns the  current epoch days.
+func (k Keeper) GetCurrentEpochDays(ctx sdk.Context) uint32 {
+	var epochDays uint32
+	store := ctx.KVStore(k.storeKey)
+	bz := store.Get(types.CurrentEpochDaysKey)
+	if bz == nil {
+		// initialize the current epoch days
+		epochDays = 1
```
[the remark this answers is not in the document]
Comment (kogisin) [reply x/farming/keeper/epoch.go:55]: Yes, I missed this part. I will fix it to set with `NextEpochDays` param.

File: x/farming/keeper/genesis.go [hunk 3]
```diff
@@ -11,6 +11,7 @@ func (k Keeper) InitGenesis(ctx sdk.Context, genState types.GenesisState) {
 	ctx, applyCache := ctx.CacheContext()
 
 	k.SetParams(ctx, genState.Params)
+	k.SetCurrentEpochDays(ctx, genState.Params.NextEpochDays)
```
[the remark this answers is not in the document]
Comment (kogisin) [reply x/farming/keeper/genesis.go:14]: I agree. Let me make the changes.

File: x/farming/spec/08_params.md [hunk 4]
```diff
@@ -7,16 +7,16 @@ The farming module contains the following parameters:
...
 
 ## PrivatePlanCreationFee
 
 Fee paid for to create a Private type Farming plan. This fee prevents spamming and is collected in in the community pool of the distribution module.
 
-## EpochDays
+## NextEpochDays
 
-The universal epoch length in number of days. Every process for staking and reward distribution is executed with this `EpochDays` frequency.
+`NextEpochDays` is the epoch length in number of days. Internally, the farming module uses `CurrentEpochDays` parameter to process staking and reward distribution in end blocker because using `NextEpochDays` directly will affect farming rewards allocation.
```
[the remark this answers is not in the document]
Comment (kogisin) [reply x/farming/spec/08_params.md:19]: Yes. I will add the following line to `spec/02_state.md` under `##Epoch` section.

```
- CurrentEpochDays: `[]byte("currentEpochDays") -> uint32`
```

**Review by dongsam — APPROVED** [review]
LGTM!

File: proto/tendermint/farming/v1beta1/farming.proto [hunk 5]
```diff
@@ -22,9 +22,10 @@ message Params {
     (gogoproto.nullable)     = false
   ];
 
-  // The universal epoch length in number of days. Every process for staking and
-  // reward distribution is executed with this epoch_days frequency
-  uint32 epoch_days = 2 [(gogoproto.moretags) = "yaml:\"epoch_days\""];
+  // next_epoch_days is the epoch length in number of days
+  // it updates internal parameter called CurrentEpochDays that is used to process
```
Comment (hallazzang) [inline proto/tendermint/farming/v1beta1/farming.proto:26]: Maybe we can use the term **internal state** instead of **internal parameter** since that is actually not a parameter.

File: x/farming/keeper/msg_server.go [hunk 6]
```diff
@@ -38,6 +39,7 @@ func (k msgServer) CreateFixedAmountPlan(goCtx context.Context, msg *types.MsgCr
 	}
 
 	plans := k.GetAllPlans(ctx)
+	fmt.Println("plans: ", len(plans))
```
Comment (hallazzang) [inline x/farming/keeper/msg_server.go:42]: This line should be removed

File: x/farming/spec/03_state_transitions.md [hunk 7]
```diff
@@ -31,10 +31,10 @@ const (
   - Each `farmingPlan` has its own `startTime` and `endTime`
 - Distribution Method
   - `FixedAmountPlan`
-    - fixed amount of coins are distributed for each `epochDays`
+    - fixed amount of coins are distributed for each `NextEpochDays`
```
Comment (hallazzang) [inline x/farming/spec/03_state_transitions.md:34]: I'm afraid if this sentence is correct, we could just say "fixed amount of coins are distributed for each `CurrentEpochDays`

File: x/farming/spec/03_state_transitions.md [hunk 8]
```diff
@@ -31,10 +31,10 @@ const (
...
     - amount in `sdk.Coins`
   - `RatioPlan`
-    - `epochRatio` of total assets in `farmingPoolAddress` is distributed for each `epochDays`
+    - `epochRatio` of total assets in `farmingPoolAddress` is distributed for each `NextEpochDays`
```
Comment (hallazzang) [inline x/farming/spec/03_state_transitions.md:37]: Comment above applies to this, too

File: x/farming/types/genesis.go [hunk 9]
```diff
@@ -37,7 +38,9 @@ func DefaultGenesisState() *GenesisState {
 		[]CurrentEpochRecord{},
 		sdk.Coins{},
 		sdk.Coins{},
-		time.Time{})
+		time.Time{},
+		1,
```
Comment (hallazzang) [inline x/farming/types/genesis.go:42]: We can use a named `const` instead of hard-coded `1`, just like `DefaultNextEpochDays`.

File: x/farming/types/params.go [hunk 10]
```diff
@@ -61,7 +61,7 @@ func (p Params) Validate() error {
 		validator func(interface{}) error
 	}{
 		{p.PrivatePlanCreationFee, validatePrivatePlanCreationFee},
-		{p.EpochDays, validateEpochDays},
+		{p.NextEpochDays, validateEpochDays},
```
Comment (hallazzang) [inline x/farming/types/params.go:64]: We can rename `validateEpochDays` to `validateNextEpochDays` too

File: x/farming/types/params_test.go [hunk 11]
```diff
@@ -44,7 +44,7 @@ func TestParamsValidate(t *testing.T) {
 		{
 			"NegativeEpochDays",
 			func(params *types.Params) {
-				params.EpochDays = uint32(0)
+				params.NextEpochDays = uint32(0)
```
Comment (hallazzang) [inline x/farming/types/params_test.go:47]: The name of the test case says it is "NegativeEpochDays" but the case uses `0` for the value. Since `NextEpochDays` is a `uint32` field, we can rename NegativeEpochDays to ZeroEpochDays.

**Review by hallazzang — CHANGES_REQUESTED** [review]
Great work. Some changes requested

File: proto/tendermint/farming/v1beta1/farming.proto (hunk 5 above)
Comment (kogisin) [reply proto/tendermint/farming/v1beta1/farming.proto:26]: You're right. I'll make that change.

File: x/farming/spec/03_state_transitions.md (hunk 7 above)
Comment (kogisin) [reply x/farming/spec/03_state_transitions.md:34]: `03_state_transitions.md` spec docs has some rooms for improvement. Let's use your sentence and handle it with another PR to improve spec documentation.

File: x/farming/types/params_test.go (hunk 11 above)
Comment (kogisin) [reply x/farming/types/params_test.go:47]: I will rename it to `ZeroNextEpochDays`
